### ISSUE TITLE
HasMany Relationship

### ISSUE THREAD

**Issue by elielcverolez** [kirschbaum-development/eloquent-power-joins#100]
I'm having problems with the HasMany Relationship,
Is there any way to merge the data brought by HasMany?
We have a table and it is related between two HasMany , as is joins , it duplicates this data that has more than one data

For example, it would be possible to bring 2 people_address
Where is the red X?
Without having to do treatment outside the query?

![image](https://user-images.githubusercontent.com/77897367/170144692-6e27fe5a-36f8-4a6a-bf84-531e64605e70.png)

It would be a great help.

**Comment by julienmru** [comment]
I have an issue related to this when using `orderByPowerJoins` on a `hasMany` relation. If the linked table as more than 1 record, I will get duplicates records on the parent table.

**Comment by luisdalmolin** [comment]
@elielcverolez That's not really a question about this package, but more related to SQL joins in general. You can bring multiple records if you use the right select statements, but it would essentially be duplicated rows. I recommend using eager loading to fetch `hasMany` records.

**Comment by luisdalmolin** [comment]
@julienmru feel free to open and issue with your issue with orderBy
