### ISSUE TITLE
Conditioning of joins is not consistent

### ISSUE THREAD

**Issue by dmikam** [kirschbaum-development/eloquent-power-joins#105]
I have these two examples:

`        $queryBuilder1 = User::query()->joinRelationship('posts.comments', [
            'posts' => function ($join) {
                $join->where('posts.published', true);
            },
        ]);
`
and
`        $queryBuilder2 = User::query()->joinRelationship('posts', [
            'posts' => function ($join) {
                $join->where('posts.published', true);
            },
        ]);
`
`dump($queryBuilder1->toSql(), $queryBuilder2->toSql());`
The only difference is the nesting o relationships... BUT... While the first one (with 'posts.comments') applies correctly where condition - the second one - ignores it completely.

**Comment by beshoo** [comment]
+1

**Comment by beshoo** [comment]
@luisdalmolin any idea?

**Comment by luisdalmolin** [comment]
This should be fixed in 3.0.0. If not, feel free to reopen
