### ISSUE TITLE
Select joined columns

### ISSUE THREAD

**Issue by stevethomas** [kirschbaum-development/eloquent-power-joins#107]
The way I have always approached joins outside of Laravel is to alias the joined columns, like:

```mysql
select products.*, users.id AS users_id, users.username as users_username, files.id AS files_id, files.path as files_path
from products
inner join users on products.user_id = users.id
inner join files on products.file_id = files.id
```
This might be a bit naive, but wouldn't there be a way to remove the column prefix and glue the related model into the product collection using `setRelation()`? Obviously the related model will be missing a bunch of attributes (no worse than ->with('users.id,username') though), and then you could easily read the relationship and access the joined model instance.

In other words; eager load via a join on one-to-one relationships and then hydrate the related model. I figure the author(s) of this package would be the people best placed to answer this 😉🤞🏻.

I'm happy to attempt a PR on this if you think it is possible.

**Comment by luisdalmolin** [comment]
Definitely not opposed of that, but as this could be a confusing feature, it would have to be some API we (maintainers) are comfortable with and won't generate a lot of issues.

**Comment by stevethomas** [comment]
No worries, totally understand. I will close this issue down and see if I can get a PR going in the near future.

**Comment by luisdalmolin** [comment]
Thanks!

**Comment by JamesPoel** [comment]
Just a note on this, if you really want to do this (like I did), then this works:

`Timesheet::joinSub(
            Timesheet::joinRelationshipUsingAlias('agency', 'agency')
                ->select([
                    'agency.title as agency_name'
                ]),
            'q', 'timesheets.id', 'id'
        )->first()->agency_name`
        
It is, of course, a little inefficient (as you have to join the table with itself) but it works.
