### ISSUE TITLE
POSTGRESQL Column alias is not supported in WHERE or HAVING clauses.

### ISSUE THREAD

**Issue by FlorianChretien** [kirschbaum-development/eloquent-power-joins#114]
Hi there,

First of all thank you for your work.

I'm starting to use your library but I'm stuck because the powerJoinWhereHas function doesn't work in my context. Having count causes the following problem: "SQLSTATE[42703]: Undefined column: 7 ERROR: column "products_count" does not existLINE 1: ...al"::text ILIKE $1 group by "castles".."id" having products_c ..." because in PGSQL you can't put an alias. You have to put the condition again so it will give "HAVING count(table.column) > 1

Do you have another solution or can you fix this issue without impacting SQL SERVER or MYSQL users?

Thanks very much,
Have a good day

PGSQL : 14
LARAVEL : 9.23
PHP : 8.1

https://www.enterprisedb.com/postgres-tutorials/how-use-tables-and-column-aliases-when-building-postgresql-query

**Comment by luisdalmolin** [comment]
Yeah, this would require some rewrites to the package which unfortunately I don't have the time for right now. I'm open to pull requests, but I'm afraid for the time being you will not be able to use this with Postgres.

**Comment by beshoo** [comment]
I would like to test a chat gpt ai to fix this.
Which file needs to be updated?

**Comment by beshoo** [comment]
Well, lets see this fix 🗡️ 

Sure, I can certainly try to help you with this issue. It sounds like you are using the powerJoinWhereHas function in the eloquent-power-joins library and you are encountering an error when using the HAVING clause with a COUNT function in a PostgreSQL database.

To fix this issue, you will need to modify the powerJoinWhereHas function to generate the correct SQL syntax for the HAVING clause when used with a COUNT function in PostgreSQL. In PostgreSQL, you cannot use an alias in the HAVING clause, so you will need to repeat the condition instead.

Here is an example of how you could modify the powerJoinWhereHas function to generate the correct syntax for the HAVING clause:


```
public function powerJoinWhereHas(Builder $query, $relation, Closure $callback, $type = 'inner', $whereNot = false)
{
    $query->{$type.'Join'}($relation, $relation.'.id', '=', $this->getTable().'.'.$this->getForeignKey());
    $query->where($relation.'.'.$this->getOwnerKey(), '=', $this->getKey());
    $query->where(function($query) use($callback, $whereNot) {
        $query->whereHas($relation, $callback, '>', $whereNot ? 0 : 1);
        // Add the following lines to generate the correct HAVING clause syntax for PostgreSQL
        if ($whereNot) {
            $query->orHavingRaw('count('.$relation.'.id) = 0');
        } else {
            $query->havingRaw('count('.$relation.'.id) > 1');
        }
    });
    return $query;
}
```
This should allow you to use the HAVING clause with a COUNT function in PostgreSQL without encountering the "undefined column" error.

I hope this helps! Let me know if you have any questions or if you need further assistance.

**Comment by beshoo** [comment]
@FlorianChretien can you test this if it works or not, If so, I think as a programmer, we need to take care of our stretchers later, it seems that someone will replace us!

**Comment by beshoo** [comment]
Well, it seems the powerJoinWhereHas is a scope "scopePowerJoinHas" I asked the AI to correct the function, it says the following:


To fix the issue you are experiencing with the powerJoinHas scope function, you will need to modify the performHavingForEloquentPowerJoins method to generate the correct syntax for the HAVING clause when used with a COUNT function in PostgreSQL.

Here is an example of how you could modify the performHavingForEloquentPowerJoins method to generate the correct syntax for the HAVING clause:


```
public function performHavingForEloquentPowerJoins(Builder $query, $operator, $count): void
{
    $relation = $this->getRelationName();
    $query->havingRaw(sprintf('count(%s.%s) %s %s', $relation, $this->parent->getKeyName(), $operator, $count));
}
```
This should allow you to use the HAVING clause with a COUNT function in PostgreSQL without encountering the "undefined column" error.

I hope this helps! Let me know if you have any questions or if you need further assistance.


================================
I don't have the problem so I can not test... LOL

**Comment by beshoo** [comment]
another fix form AI LOL


To fix the issue you are experiencing with the powerJoinWhereHas function, you can modify the performHavingForEloquentPowerJoins function as follows:


```
public function performHavingForEloquentPowerJoins()
{
    return function ($builder, $operator, $count) {
        $builder
            ->selectRaw(sprintf('count(%s) as %s_count', $this->query->getModel()->getQualifiedKeyName(), $this->query->getModel()->getTable()))
            ->havingRaw(sprintf('count(%s) %s %d', $this->query->getModel()->getQualifiedKeyName(), $operator, $count));
    };
}
```
This will remove the alias for the count function, and instead use the original column name in the HAVING clause. This should work with PostgreSQL, as well as with other database systems that do not allow using aliases in the HAVING clause.

Note that this change might impact the performance of the query, as the count function will be evaluated for each row in the result set. If the performance of the query is a concern, you may want to consider alternative solutions, such as using a subquery or a JOIN with a GROUP BY clause.

I hope this helps! Let me know if you have any further questions.

**Comment by FlorianChretien** [comment]
Hi beshoo,

**It works thank you very much!**
Indeed this can have a performance problem, a simple join without having could be enough in itself.

Another question, do you plan to create the orPowerJoinWhereHas function?

thanks again

**Comment by FlorianChretien** [comment]
In my case, I put 3.69s with the library and 2.10s when writing the joins by hand (so without having). So I think I'll drop the bookstore. thanks anyway

**Comment by beshoo** [comment]
> Hi beshoo,
> 
> **It works thank you very much!** Indeed this can have a performance problem, a simple join without having could be enough in itself.
> 
> Another question, do you plan to create the orPowerJoinWhereHas function?
> 
> thanks again

You mean performHavingForEloquentPowerJoins ?

**Comment by FlorianChretien** [comment]
For performance I'm talking about performHavingForEloquentPowerJoins, yes :)

**Comment by beshoo** [comment]
@luisdalmolin am not sure why I can not create a PL, please can you update the file.

**Comment by luisdalmolin** [comment]
@beshoo To create a pull request you will have to fork the repo to your account, push the code and then create the PR
