### ISSUE TITLE
Nested where in joinRelationship callback breaks when using a scope.

### ISSUE THREAD

**Issue by arielhs** [kirschbaum-development/eloquent-power-joins#117]
Hi,

**Jump to the end to see the small change i believe will fix this**

I'm on Laravel 9.38.0, and version 2.6.5 of this library. 

There is an issue if you try to use a nested where within the join of a joinRelationship call, and what you do in that nested where relies on accessing something on your joined-to-relationship model (e.g. a scope). A simplified version of my use-case:

```
class Post extends Model
{
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function scopeWhereApproved($query)
    {
        return $query->where('approved', true);
    }
}

class Comment extends Model
{
    public function post()
    {
        return $this->belongsTo(Post::class);
    }
}

Comment::joinRelationship('post', function ($join) {
    $join->whereApproved(); // ✅ works fine
});

Comment::joinRelationship('post', function ($join) {
    $join->where(function($innerQuery) {
        $innerQuery->where('post_colour', 'red'); // ✅ also works since it's a "normal" where
    });
});

Comment::joinRelationship('post', function ($join) {
    $join->where(function($innerQuery) {
        $innerQuery->whereApproved(); // ❌ Error: using a scope on the Post model does not work
    });
});
```

In my example, the exception thrown:

```
 method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given
 at vendor/kirschbaum-development/eloquent-power-joins/src/PowerJoinClause.php:189

 ➜ 189▕         if (method_exists($this->getModel(), $scope))
```

I've tracked the issue down, `$innerQuery` is indeed a `PowerJoinClause` instance, with the correct `$table` property set (as with the outer `$join` value), but the `$model` has not been set.

The cause is that when you do a nested where like this, Laravel's Builder class has a call like this:

```
    public function forNestedWhere()
    {
        return $this->newQuery()->from($this->from);
    }
```

In this context, `$this` is a PowerJoinClause instance for our `Post` model.

Following this further, `$this->newQuery()` hits this in Laravel's `JoinClause` class:

```
    public function newQuery()
    {
        return new static($this->newParentQuery(), $this->type, $this->table);
    }
``` 

This still news up another `PowerJoinClause` for our `Post` join, but the final parameter `$model` for the constructor is missing.

The fix is seemingly simple, we just need to override the `JoinClause.newQuery()` method in `PowerJoinClause`:

```
class PowerJoinClause extends JoinClause
{
...

    public function newQuery()
    {
        return new static($this->newParentQuery(), $this->type, $this->table, $this->model); // <-- The model param is needed
    }
...
}
```

I've hacked my own temporary solution in my project by extending `PowerJoinClause` and overriding `newQuery` like i described above, and it seems to be working fine. I'm not confident enough in the side-effects of this change to make a PR. Let me know if you think its fine.

**Comment by luisdalmolin** [comment]
Thanks for the suggestion, it helped with the fix. This fix is going to be included in the next release.

**Comment by liuyong888** [comment]
@luisdalmolin hi，Bro I need it badly for my work。When do you need to fix it, pelase

**Comment by luisdalmolin** [comment]
It's included in the latest release.

**Comment by liuyong888** [comment]
> https://github.com/kirschbaum-development/eloquent-power-joins/releases/tag/2.7

> It's included in the latest release.

Thanks.
