### ISSUE TITLE
orderByUsingJoins does not get the correct latest relationship model for nested relationships

### ISSUE THREAD

**Issue by travisobregon** [kirschbaum-development/eloquent-power-joins#12]
The following looks for the latest relationship name from the root model of the query.
https://github.com/kirschbaum-development/eloquent-power-joins/blob/e6c7011be14d83dfad1bace18226a8d9b1cc5542/src/Mixins/JoinRelationship.php#L190-L192

The following query from the tests works because there is a comments relationship defined on the User model.
https://github.com/kirschbaum-development/eloquent-power-joins/blob/e6c7011be14d83dfad1bace18226a8d9b1cc5542/tests/OrderByTest.php#L36-L37

If you comment out the comments relationship, you will get the following error:
> Call to undefined method KirschbaumDevelopment\EloquentJoins\Tests\Models\User::comments()

Or if you try this query, it will fail:
`User::orderByUsingJoins('posts.category.title', 'desc')->get();`

**Comment by luisdalmolin** [comment]
@travisobregon Seems like a valid issue. I'll take a look at this probably tomorrow or over the weekend and keep you posted. Thanks for the report.

**Comment by travisobregon** [comment]
@luisdalmolin No worries. I have just submitted a PR #13.

**Comment by luisdalmolin** [comment]
@travisobregon Just tagged 1.1.1 with your fix.
