### ISSUE TITLE
Bad column name when using alias if the table and the field has the similars name

### ISSUE THREAD

**Issue by Runig006** [kirschbaum-development/eloquent-power-joins#121]
Kirschbaum\PowerJoins\PowerJoinClause in the function useTableAliasInConditions() line 120 it make a str_remplace, but it doesnt limit it to the table, so it remplace everything with the same name

If you have table shop and the field is shopId the field will transform to Alias.AliasId and not alias.shopId

.Net by default create the primarys keys like that, tableName and tableNameId as primary key

**Comment by luisdalmolin** [comment]
Hi @Runig006, thanks for the report. We'll take a look at this at some point, but if you have any urgency with this fix, we are also open to pull requests.

**Comment by Runig006** [comment]
I dont want to lie...urgency yes, that why i made a fork. 

I know what i can changes for my needs, but i dont know if i can broke any one projects...because i don´t know all the scope of the project.

I make the pull request anyway, but I don't know if the change is risky or not.

I have another issue with the alias...but is more dificult to explain, in case you see the fork and see that there is one commit more

**Comment by luisdalmolin** [comment]
Just tagged a new release including your fix: https://github.com/kirschbaum-development/eloquent-power-joins/releases/tag/2.7.3

Thanks for the contribution.
