### ISSUE TITLE
Support for hasOne()->ofMany

### ISSUE THREAD

**Issue by ederuiter** [kirschbaum-development/eloquent-power-joins#126]
When defining a relation with `->hasOne()->ofMany()`, it would be nice to automatically add the inner filter + aggregation.

For example we have a order model with the following relations:

```php
class Order extends Model
{
    use PowerJoins;

    public function plan()
    {
        return $this->hasOne(OrderLine::class)->ofMany(['id' => 'MAX'], function ($query) {
            $query->where('type', '=', 'plan');
        })
    }
    
    public function lines()
    {
        return $this->hasMany(OrderLine::class);
    }
}
```
The idea is we can have multiple orderlines, but the `plan` relation filters the one with `type="plan"` and since we cannot guarantee (from a db perspective) that there is only one plan we need a group by.

We can use the `plan` relation to filter on the plan by using something like:

```php
Order::query()->whereRelation('plan', 'name', '=', 'test');
```
which generates this (awful) query
```mysql
 select * from `orders` where exists (select * from `order_lines` inner join (select MAX(`order_lines`.`id`) as `id_aggregate`, `order_lines`.`order_id` from `order_lines` where `type` = ? group by `order_lines`.`order_id`) as `plan` on `plan`.`id_aggregate` = `order_lines`.`id` and `plan`.`order_id` = `order_lines`.`order_id` where `orders`.`id` = `order_lines`.`order_id` and `name` LIKE ? and `type` = ?)
```

With a powerjoin (for the sorting) the group by + inner filter are both ignored.

```sql
select `orders`.* from `orders` inner join `order_lines` on `order_lines`.`order_id` = `orders`.`id` order by `order_lines`.`product_variant_id` asc
```

For now we can workaround it since the laravel `whereRelation/whereHas` seems to ignore the outer where filter on the `hasOne()->ofMany()` relation and the powerjoins seems to use that and ignore the inner stuff.
But it is more of a happy accident this works (as it is not adding group by)

```php
    public function plan()
    {
        return $this->hasOne(OrderLine::class)->ofMany(['id' => 'MAX'], function ($query) {
            $query->where('type', '=', 'plan');
        })->where('type', '=', 'plan');
    }
```

It would be nice if this can be directly supported by powerjoins; although looking at the laravel source it does not really seem possible to extract the inner callback

Or is there a better to define such a relationship that it would work nicely with powerjoins?

**Comment by luisdalmolin** [comment]
Hmm yeah we should definitely support the has one of many relationship type. I'll look into it but cannot give a clear timeline.

**Comment by luisdalmolin** [comment]
This was added in version 3.2.0.
