### ISSUE TITLE
SQLSTATE[HY093]: Invalid parameter number

### ISSUE THREAD

**Issue by francoism90** [kirschbaum-development/eloquent-power-joins#128]
I'm trying to load a polymorphic relationship using your package:
```php
$query = Post::query()
    ->with(['media', 'tags'])
    ->joinRelationshipUsingAlias('media', 'foo');
```
Results: Invalid parameter number

This Laravel code works:
```php
$query
            ->select('posts.*') // this is needed, otherwise ambiguous error
            ->join('media', function (JoinClause $join) {
                $join
                    ->on('posts.id', '=', 'media.model_id')
                    ->where('media.collection_name', 'pdf');
            })
 ```
Do I need something different?

Thanks

**Comment by luisdalmolin** [comment]
@francoism90 Can you post the full error message you are getting?

**Comment by francoism90** [comment]
@luisdalmolin This is basically the full message. :)

If it helps, I'm using Spatie's Media Library on a simple Eloquent Post model with the latest MariaDB.

**Comment by luisdalmolin** [comment]
Sorry for the delay, but this should be fixed now :)

Feel free to reopen this issue if not.

**Comment by francoism90** [comment]
@luisdalmolin Just to confirm, it indeed seems to be fixed. :)

Thanks a lot!
