### ISSUE TITLE
Joining polymorphic relationships

### ISSUE THREAD

**Issue by badasukerubin** [kirschbaum-development/eloquent-power-joins#129]
Hi, excellent package. I read the doc for polymorphic relationships but it doesn't seem to work.
Say I have a model `Users` with a polymorphic relationship to `Pictures` and `Videos`, I can declare 
```php
public function media(): MorphTo
{
    return $this->morphTo();
}
```
which morphs into both relations using `media_type` and `media_id`. According to the doc - I think, I should be able to sth like:
`User::joinRelationship('pictures');` but this throws BadMethodCallException for pictures as it's not actually a method in the User model.
Am I missing something? Is this action possible with the package?

**Comment by luisdalmolin** [comment]
@badasukerubin Sorry for the long response time here. Can you please provide the code for all the relationships here? You should definitely be able to do `User::joinRelationship('pictures')`. Did you add the `PowerJoins` trait to the model?

**Comment by brunolopesr** [comment]
@badasukerubin 

Do you think it is really a polymorphic relationship you need in your scenario? If it is, it seems something like this:

```
users
    id - integer
    media_id - integer
    media_type - string

videos
    id - integer

pictures
    id - integer
```

If you declare the relationship method as `media` calling `morphTo`, you should use `User::joinRelationship('media')`

Please review the need for a polymorphic relationship, if a user can have many `Picture` and `Video`, you need a normal `One-to-Many` relationship using `user_id` foreign keys in `pictures` and `videos` tables.

**Comment by luisdalmolin** [comment]
@badasukerubin Closing this for now, feel free to reopen when you answer.
