### ISSUE TITLE
Feature request: Power Joins on custom query builder

### ISSUE THREAD

**Issue by kavihGB** [kirschbaum-development/eloquent-power-joins#130]
Hello dev team. I appreciate this package. In a project, I have my own builder (that extends `Illuminate\Database\Query\Builder`). I'd like to do something like `$builder->joinRelationship()`, which I would expect to function the same as `User::select('id')->joinRelationship()`. I understand this package already adds mixins/macros to `Illuminate\Database\Query\Builder`, but I do not see how I can replicate those onto my custom builder, so that `$builder->joinRelationship()` resolves. Any help would be really appreciated. Thanks.

**Comment by kavihGB** [comment]
A bit more info of why I would want this: I can't control how data will be fetched, besides knowing it will go through my custom builder. So, it could be something like `DB::table('users')->joinRelationship()`.

**Comment by luisdalmolin** [comment]
Well, this package is heavily tied into the Eloquent relationships. The whole purpose is to use relationship definitions to make joins easier and hide implementation details, so I don't see how this being available in the query builder alone would be useful? Where it would grab the relationship data?

I'm closing this, but feel free to reopen if you have a valid use case from what I described.
