### ISSUE TITLE
`JoinRelationship` mixin vs `PowerJoins` trait

### ISSUE THREAD

**Issue by GeoSot** [kirschbaum-development/eloquent-power-joins#131]
Just a question here.

I found out that `JoinRelationship` is being registered automatically, but in contradiction `PowerJoins` trait, has to be inserted manually. 

![image](https://user-images.githubusercontent.com/22406063/236494939-26fba367-a2bb-41a7-8fb7-3bdb4a3e74e1.png)

Normally It would be fine.
However, `PowerJoins` trait registers only a series of scopes (functions that are being checked from Builder and etc etc etc)
It would be fine again till the moment I faced the following problem

![image](https://user-images.githubusercontent.com/22406063/236486244-7747f60d-9025-432c-9884-d1a13a46b13b.png)

The first `when` case provides autocompletion, but it is invalid as `when` is being called on builder . The second case comes with the exact opposite problem
Of course, I can typehint both `Builder|Model`, but after this, phpStan complains that I cannot return a Model, so any method-chain  after this, seems wrong.

Registering all  `PowerJoins` trait's methods from `JoinRelationship` mixin, would solve the problem, but the question is, "Would be a valid implementation?"

**Comment by luisdalmolin** [comment]
Sorry for the delay in answering this. The real answer is that this may not be so simple, but I'll take a look at what can be done to improve this.

**Comment by luisdalmolin** [comment]
@GeoSot Did you confirm that your PR fixes the auto-completion issues you were having? I'm not convinced this will work

**Comment by GeoSot** [comment]
@luisdalmolin I have attached some pictures to prove the tests I've done, and it works fine on phpstan check

**Using main-branch:** PhpStan using `Builder|Model` as typed argument
![image](https://github.com/kirschbaum-development/eloquent-power-joins/assets/22406063/1518d22d-8799-4a99-9a6f-afca950169e0)

**Using main-branch:** PhpStan using `Builder` as typed argument
![image](https://github.com/kirschbaum-development/eloquent-power-joins/assets/22406063/a451a000-2e79-4df0-99ec-70fba5559d4c)


**Using fix-branch:** PhpStan  using `Builder` as typed argument
![image](https://github.com/kirschbaum-development/eloquent-power-joins/assets/22406063/9fdfa19d-dbd9-4260-b530-0663f2f16879)

The only 'glitch' I don't get till now, is that ide-helper has achieved to declare the method correct, however ide (phpstorm), is not able to find it. ( I suppose I can try to solve it in a following PR, as the quality tests are passing with success )
![image](https://github.com/kirschbaum-development/eloquent-power-joins/assets/22406063/d2bb47de-443a-4000-8848-ff26651f10e3)
