### ISSUE TITLE
Incompatibility with Laravel scopes

### ISSUE THREAD

**Issue by amshehzad** [kirschbaum-development/eloquent-power-joins#133]
Hi, first of all,
thank you for this great package! it saves me a lot of time and coding.
I just noticed a small issue, I'm using Laravel 10, and using scope with the type 
`use Illuminate\Database\Eloquent\Builder`

this throws an error 

`App\Models\Leave::scopeApproved(): Argument #1 ($builder) must be of type Illuminate\Database\Eloquent\Builder, Kirschbaum\PowerJoins\PowerJoinClause given, called in E:\Laravel\osneo\vendor\kirschbaum-development\eloquent-power-joins\src\PowerJoinClause.php`

Any possibility to fix ? or I just drop the type of builder ?

Thank you

**Comment by luisdalmolin** [comment]
Hmm, yeah this is not as simple as it could be, because the Laravel base Join class, which PowerJoinClause extends, extends the Database builder class, not the eloquent. The ideal way is to add both type-hints. I'm going to add a section on the docs about this.
