### ISSUE TITLE
Nested calls is not work

### ISSUE THREAD

**Issue by liuyong888** [kirschbaum-development/eloquent-power-joins#134]
laravel/framework: v8.57
kirschbaum-development/eloquent-power-joins: 2.7.3

User::joinRelationship('posts.comments', [
    'posts' => function ($join) {
        $join->where('posts.published', true);
    },
    'comments' => function ($join) {
        $join->where('comments.approved', true); // IS NOT WORK!
    }
]);
@kirschbaum @luisdalmolin

**Comment by luisdalmolin** [comment]
I just made a test with the same exact code and it worked just fine. Please provide more details and reopen if you have more.
