### ISSUE TITLE
Cloning query breaks duplicate relationship join prevention

### ISSUE THREAD

**Issue by tobyzerner** [kirschbaum-development/eloquent-power-joins#145]
Introduced in 3.1.0.

Minimal reproduction:

```php
$query = Post::query();
$query->leftJoinRelationship('author');
$query->clone()->leftJoinRelationship('author')->get();
```

Results in the author relationship being joined twice, which causes an SQL error.

**Comment by luisdalmolin** [comment]
@tobyzerner interesting, this was working before?

**Comment by luisdalmolin** [comment]
Ok yeah this was introduced in https://github.com/kirschbaum-development/eloquent-power-joins/pull/135. I'll take a look at it.

**Comment by luisdalmolin** [comment]
This should be fixed in the latest version.
