### ISSUE TITLE
whereHasUsingJoins fails inside model scopes

### ISSUE THREAD

**Issue by luisdalmolin** [kirschbaum-development/eloquent-power-joins#15]
When using `whereHasUsingJoins` inside a model scope, it fails as Laravel tries to use dynamic wheres instead of using the proper method. Need to figure out a good approach for this, but may need to ship a new version where we include a trait in the models instead of adding macros due to how Laravel works.

**Comment by luisdalmolin** [comment]
This is now fixed :)

**Comment by itsensepk** [comment]
Please update your article https://kirschbaumdevelopment.com/insights/power-joins, its really a great guide.

Thanks for the package!
