### ISSUE TITLE
powerJoinWhereHas multi-level

### ISSUE THREAD

**Issue by Stevemoretz** [kirschbaum-development/eloquent-power-joins#157]
While the multi-level works, the callbacks need a bit more documentations, the call back runs for each of the levels meaning you have to conditionally run it on your own preferred levels, yourself.

Here's a useful example I wish there was in the docs so I didn't have to debug and find it out myself:

```php
return $builder->powerJoinWhereHas("order.users", function (PowerJoinClause $join){
    if($join->wheres[0]["second"] === "users.id"){
        return $join->where("users.id", "=", auth()->id());
    }
    return $join;
});
```

The above `$join->where("users.id", "=", auth()->id());` only runs now on `users` relationship as opposed to running also on `order`. I'm doing the condition on `$join->wheres[0]["second"]` maybe there is a better and cleaner condition to use but this definitely works.

**Comment by luisdalmolin** [comment]
I just released and documented this, but on the latest version, you can do:

```php
return $builder->powerJoinWhereHas("order.users", [
    'users' => fn ($join) => $join->where("users.id", "=", auth()->id()),
]);
```
