### ISSUE TITLE
joinRelationship - get relation data

### ISSUE THREAD

**Issue by ApXaHgheJI** [kirschbaum-development/eloquent-power-joins#167]
Hey, following question:

I have an relation ManyToMany - and for one of the Entity - I try to load all the relations from second table using `joinRelationship`

the issue that I face, is that the data is not populated automatically - yes - the query raw is join, but the actual select is populating main table and not joined one.

adding to select ( second table ) - is causing an issue because we have an column `id` that is unique.

Question: There is a way to join data based on relation `joinRelationship` - and autopopulate/fill it as an property of entity ?

Example:

UserTable has many PostsTable

UserTable ( has an relation ) - posts(belongsToMany).

$entities = UserTable::joinRelationship('posts')->get()->first();

$entities->post ( will be already populated without additional join that is made by Laravel ) ?

Best regards.

**Comment by luisdalmolin** [comment]
This package is not a replacement of eager loading. Please do some research on how joins work behind the scenes if you need more information. In short, if you want the fields of the post, you have to manually select them

e.g.

```php
UserTable::select('users.*', 'posts.title', 'posts.body')->joinRelationship('posts')->first();
```

**Comment by ApXaHgheJI** [comment]
that is the issue, that using eager loading - is completely removes the idea to use this joinRelationship's - ( only in case when you need to use the condition ) 
But if you need to get data according to condition in join, this functionality become unuseful :(

an example in Yii Framework ( when there is used an relation - its automatically populated in object element - that is allowing you to use and condition and data ) 

IMHO.

**Comment by luisdalmolin** [comment]
That could be a feature we eventually add here, but it's not in the current plans and brings so many complexities. I also think if you are loading a has many relationship, the eager loading is your best choice. Even 2 queries should be faster than one joined one.
