### ISSUE TITLE
Does not work with the method withoutGlobalScopes

### ISSUE THREAD

**Issue by ezequidias** [kirschbaum-development/eloquent-power-joins#168]
The join is not working when using withoutGlobalScopes

example: 

```PHP
public function document()
{
    return $this->belongsTo(UserDocument::class)->withoutGlobalScopes();
}
````

**Comment by luisdalmolin** [comment]
@ezequidias Can you please provide the full code snippet and what you are expecting? This package doesn't automatically include global scopes in the joins. To do so, you have to explicitly call it, e.g.:

```php
UserProfile::joinRelationship('users', fn ($join) => $join->withGlobalScopes());
```

**Comment by ezequidias** [comment]
Thanks! I thought it was automatic!
