### ISSUE TITLE
orderByUsingJoins missing results

### ISSUE THREAD

**Issue by MikeyAlder** [kirschbaum-development/eloquent-power-joins#17]
When using Model::orderByUsingJoins() you use an inner join query, however, this causes rows to be missing if they don't have the required relationship filled.

Is there are way to use left joins when using Mode::orderByUsingJoins()?

**Comment by luisdalmolin** [comment]
Not currently, but it's a feature we can add to the package for sure. I'll be working on some issues and probably a new major version over the next days and I'll keep this feature in mind.

**Comment by MikeyAlder** [comment]
Brilliant! I had created a orderByUsingLeftJoins method, that switched the joins, for now and was going to create a pull request. But if you are working on a major overhaul I won't bother as I'm sure your solution will be much better than my hack 😂.

**Comment by luisdalmolin** [comment]
@MikeyAlder This should now be fixed in version 2.0. Make sure you check the new method signature for 2.0. as well that you now have to use a trait in your model. This version is already ready to support Laravel 8 as well.
