### ISSUE TITLE
Upgrading from 3.2.1 to 3.5.0 produces error "Undefined column: 7 ERROR"

### ISSUE THREAD

**Issue by vedmant** [kirschbaum-development/eloquent-power-joins#172]
Hi, I have following code 

```php
$boards = Board::with('last_activities', 'last_activities.actable', 'last_activities.addable', 'user', 'posts', 'posts.is_bookmarked', 'media')
                       ->where('visibility', '!=', 'unlisted')
                       ->orderByPowerJoinsMax('activities.created_at', 'desc')->take(10)->get();
```

It works ok on 3.2.1, but after upgrading to 3.5.0 stared to error:

```
SQLSTATE[42703]: Undefined column: 7 ERROR:  column "activities_created_at_MAX" does not exist
LINE 1: ...visibility" != $2 group by "boards"."id" order by "activitie...
                                                             ^ (Connection: pgsql, SQL: select "boards".*, MAX(activities.created_at) as activities_created_at_MAX from "boards" inner join "activities" on "activities"."actable_id" = "boards"."id" and "activities"."actable_type" = boards where "visibility" != unlisted group by "boards"."id" order by "activities_created_at_MAX" desc limit 10)
```

I tested the query and looks like the issue is due to `activities_created_at_MAX` is wrapped in double quotes `""`.

Versions:

"laravel/framework": "^10.0" - 10.48.3
"kirschbaum-development/eloquent-power-joins": "3.2.1",

PHP 8.3.4
PostgreSQL 14.2 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit

**Comment by luisdalmolin** [comment]
Hmm, this seems to be a problem specific to PostgreSQL. The quotes are not being added directly by the package, but I will try to take a look at it.

**Comment by vedmant** [comment]
@luisdalmolin Something has to be with updates in the package, version 3.2.1 works ok, not sure which version actually breaks it.

**Comment by luisdalmolin** [comment]
@vedmant In theory, no changes would affect this. Was your Laravel version also upgraded with this upgrade?

**Comment by vedmant** [comment]
@luisdalmolin No, just checked, upgraded only this package to 3.5.0 and error appeared. Downgraded to 3.2.1 - disappeared. Tested other versions, error starts from 3.2.2.

**Comment by vedmant** [comment]
@luisdalmolin Looks like specifically this line crates an error: `[src/Mixins/JoinRelationship.php](https://github.com/kirschbaum-development/eloquent-power-joins/compare/3.2.1...3.2.2#diff-c0f6ec229bc52f723798ab5b9a342530409eb2091f00a2c170940d3270ea4719):337` `'%s(%s.%s) as %s',`

**Comment by vedmant** [comment]
@luisdalmolin Not sure what changing `%s_aggregation` to `%s` was for, but if I can just revert this line I can make a PR.

**Comment by luisdalmolin** [comment]
Interesting, yes, feel free to make a PR with this change, if it was for any important change tests should fail.

**Comment by vedmant** [comment]
@luisdalmolin Actually formatting was not the case, fixed it by passing raw alias name for ordering, I added a PR https://github.com/kirschbaum-development/eloquent-power-joins/pull/174
