### ISSUE TITLE
**Error in powerJoinHas POSTGRE**

### ISSUE THREAD

**Issue by wpj16** [kirschbaum-development/eloquent-power-joins#176]
**Error in powerJoinHas POSTGRE**

Error description:

Postgre allows you to create database schemas, ( name_schema.name_table ), when modifying the $table attribute in the model, to the default ( name_schema.name_table ), the error occurs in the counter alias ( schema.table_count ) syntax error at or near ".";
    
      File: Kirschbaum\PowerJoins\Mixins\RelationshipsExtraMethods;
      Method: performHavingForEloquentPowerJoins

Possible Solution:

In the performHavingForEloquentPowerJoins method, all aliases that use ( ->getTable() ) must be treated.
   a replace must be added, correcting point by undeline

     In:
        sprintf('count(%s) as %s_count', $modelInstance->getQualifiedKeyName(), $modelInstance->getTable())
     For:
      sprintf('count(%s) as %s_count', $modelInstance->getQualifiedKeyName(),str_replace('.','_',$modelInstance->getTable()))

**Comment by luisdalmolin** [comment]
Makes sense. I just pushed a new version including this change, can you let me know if it fixes it?

**Comment by wpj16** [comment]
> performHavingForEloquentPowerJoins

Successfully resolved, thank you very much and congratulations on the lib, it works very well.
