### ISSUE TITLE
Error when filtering in PowerJoinClause

### ISSUE THREAD

**Issue by wpj16** [kirschbaum-development/eloquent-power-joins#177]
Error when filtering in PowerJoinClause

Query:

`$query = Cart::query()->joinRelationship('checkout', fn ($join) => $join->as('checkout')->whereIndexes(1));
`

Error description:

> Method whereIndexes does not exist in PowerJoinClause class.

Laravel has the functionality to customize the eloquent builder class (newEloquentBuilder method in the model).

The parameter passed to the join query is not of the eloquent builder type, so it does not have the custom method (whereIndexes) that I created in the builder.

Possible solutions:

1. Pass the extended builder as a parameter.

2. PowerJoinClause assign a method ( ->getBuilder() ) that returns the eloquent builder of the model that was joined, so that you can continue assigning the conditions in the "ON" option of the join.

Something like:

` $query = Cart::query()->joinRelationship('checkout', fn ($join) => $join->as('checkout')->getBuilder()->whereIndexes(1));`

**Comment by luisdalmolin** [comment]
Yeah, that never was implemented. It was simple to add this feature, so I just tagged a new version, can you test it?
