### ISSUE TITLE
Custom eloquent builder fix

### ISSUE THREAD

**Issue by wpj16** [kirschbaum-development/eloquent-power-joins#178]
Yeah, that never was implemented. It was simple to add this feature, so I just tagged a new version, can you test it?

_Originally posted by @luisdalmolin in https://github.com/kirschbaum-development/eloquent-power-joins/issues/177#issuecomment-2021289497_

It worked correctly.

All that remains is to initialize (the model that was joined) and assign it to the eloquent builder ( $builder->setModel( new ModelJoin() ) )

**Comment by wpj16** [comment]
![image](https://github.com/kirschbaum-development/eloquent-power-joins/assets/17207754/4d884450-25b4-4c2b-b964-ad672392a60a)

In the image, within the builder, you can see that the getModel() method is often used, both in the custom and official builder.

So I think all that remains is to pass the instance of the model that was joined to the setModel() method of the builder.

**Comment by luisdalmolin** [comment]
Good point, added and tagged a new release.

**Comment by wpj16** [comment]
> Bom ponto, adicionado e marcado um novo lançamento.

working perfectly, thanks for the updates
