### ISSUE TITLE
Quoting bug

### ISSUE THREAD

**Issue by MiruTights** [kirschbaum-development/eloquent-power-joins#184]
I have a query:
```php
Place::query()
->powerJoinDoesntHave('storageContainers')
->get()
```

Err:
SQLSTATE[42P01]: Undefined table: 7 ERROR: missing FROM-clause entry for table "storagecontainers" LINE 1: select "places".*, count(storageContainers.id) as storageCon..
generated sql query:

```sql
SELECT
  "places".*,
  count(storageContainers.id) AS storageContainers_count
FROM
  "places"
  LEFT JOIN "storageRelations" ON "storageRelations"."place_id" = "places"."id"
  LEFT JOIN "storageContainers" ON "storageContainers"."storageRelation_id" = "storageRelations"."id"
WHERE
  "places"."deleted_at" IS NULL
GROUP BY
  "places"."id"
HAVING
  count(storageContainers.id) < 1
```

It's missed quoting `"storageContainers"` in `count(storageContainers.id)`

**Comment by luisdalmolin** [comment]
@MiruTights Which database are you using?

**Comment by MiruTights** [comment]
> @MiruTights Which database are you using?

PostgreSql

**Comment by luisdalmolin** [comment]
@MiruTights I can't replicate this issue in Postgres, if you can submit a repo replicating the bug I'm happy to take a look. Feel free to reopen, I'm closing the issue for now.
