### ISSUE TITLE
defined return types prevent IDE from autocompleting

### ISSUE THREAD

**Issue by azgooon** [kirschbaum-development/eloquent-power-joins#186]
Hi,

I checked resolved issues and no one brought this up so I think I am just missing the puzzle rather than reporting an issue.
I noticed that when I use i.e joinRelation() method in my laravel project, the chained method (ie groupBy()) afterwards is marked as not defined.
This is because joinRelation() returns closure instead of Builder instance.
What is the best way to overcome this issue and make IDE "understand" that joinRelation() returns Query Builder and can be chained?

![image](https://github.com/user-attachments/assets/5c8f465c-c362-49c8-8b21-cde4d1fedab1)

Thanks,
Tom.

**Comment by luisdalmolin** [comment]
The best way (right now) to overcome this is to add this to your model as a docblock (make sure to use the right model name):

```php
/**
 * @method static \Illuminate\Database\Eloquent\Builder|User joinRelation(string $relationName, \Clousure|array$callback = null, string $joinType = 'join', bool $useAlias = false, bool $disableExtraConditions = false, string $morphable = null)
 */
class User extends Model
{
}
```

**Comment by azgooon** [comment]
@luisdalmolin this works a treat - thank you very much.
