### ISSUE TITLE
im try to install and get this error:

### ISSUE THREAD

**Issue by maiconmva** [kirschbaum-development/eloquent-power-joins#19]
im try to install and get this error:

In ProviderRepository.php line 208:

  Class 'KirschbaumDevelopment\EloquentJoins\PowerJoinsServiceProvider' not found

**Comment by Kubinoyok0** [comment]
Because developer change namespace of this package.

Exclude this package from auto-discovery.
==== composer.json ====
"extra": {
        "laravel": {
            "dont-discover": [
                "kirschbaum-development/eloquent-power-joins"
            ]
        }
    },
==================

Add it in service provider manually in "config/app.php". 

Please use these solution until developer fix it.

**Comment by luisdalmolin** [comment]
Thanks @Kubinoyok0. 

I have just pushed the fix and tagged as 2.0.1 @maiconmva, completely missed that.
