### ISSUE TITLE
Power join on MorphTo relations does not work since Laravel v11.33.0

### ISSUE THREAD

**Issue by sebj54** [kirschbaum-development/eloquent-power-joins#191]
### Description

Hi there,

Since version 11.33.0 and more precisely this commit: https://github.com/laravel/framework/commit/8528d04598f99f7cfa0f0aab56c170f8fd583024, the constraints applied on `MorphTo` relations have changed.

For the example, let's say I have the example relation from the docs: https://laravel.com/docs/11.x/eloquent-relationships#one-to-one-polymorphic-model-structure. So I have an `Image` model with an `imageable` relation (`MorphTo`), pointing to a `Post`.

Before that commit, the foreign key constraint was correctly added to the relation query: it added a where like this: 

```
[
        "type" => "Basic"
        "column" => "posts.id"
        "operator" => "="
        "value" => 252
        "boolean" => "and"
]
```

Now with the latest version, the only where is:

```
[
        "type" => "Null"
        "column" => ""
        "boolean" => "and"
]
```

This bug breaks the MorphTo relations joined with this package.

I previously opened an issue on Laravel's repo but it has been closed: https://github.com/laravel/framework/issues/53624

### Reproduction

I also created a repo with a reproduction: https://github.com/sebj54/laravel-morphto-bug

There is a test in `tests/Feature/MorphToTest.php`:

```php
public function test_morph_to_can_user_power_join(): void
{
    $post = Post::factory()->create();

    $image = Image::factory()
        ->for($post, 'imageable')
        ->create();

    $results = Image::joinRelationship('imageable', morphable: Post::class)
        ->get();

    $this->assertCount(1, $results);
    $this->assertTrue($results->contains($image));
}
```

```
php artisan test tests/Feature/MorphToTest.php --filter test_morph_to_can_user_power_join
```

This code works on previous Laravel versions, you can check it out by moving to `11.32` branch:

```
git switch 11.32
composer update
php artisan test tests/Feature/MorphToTest.php --filter test_morph_to_can_user_power_join
```

You can see that the test pass correctly.

### Additional details

If you dump the SQL query, you can see that `and "" is null` is added to it, breaking the join.

```php
$results = Image::joinRelationship('imageable', morphable: Post::class)
    ->dumpRawSql()
    ->get(); 
```

```sql
select "images".* 
from "images" 
inner join "posts" on "images"."imageable_id" = "posts"."id" 
    and "images"."imageable_type" = 'App\Models\Post' 
    and "" is null
```

This is due to the additional constraint added to the relation query. Since there was already a similar constraint on the relation query, I guess there is a hard check in this repo to avoid the empty constraint but it has to be updated.

I would be glad to submit a PR for this, but I need some hints about the location of the hard check (if I'm right).

**Comment by luisdalmolin** [comment]
Oh damn, we'll look into this today. Thanks for the detailed issue. The place where this needs to be changed is likely on `RelationshipsExtraMethods`, but possibly on `PowerJoinClause` as well if you want to explore the fix

**Comment by sebj54** [comment]
I just submitted a PR, it was a pretty easy fix! I let the existing check alongside the one I added so previous Laravel versions are still functioning.
