### ISSUE TITLE
wrong relational

### ISSUE THREAD

**Issue by maiconmva** [kirschbaum-development/eloquent-power-joins#20]
hello can you see it, is a bug?

https://prnt.sc/uag1yq

![image](https://user-images.githubusercontent.com/5194641/92028257-1ede6980-ed3a-11ea-8974-00acf6dd65fe.png)

**Comment by luisdalmolin** [comment]
@maiconmva Thanks for reporting, I'll take a look tonight.

**Comment by maiconmva** [comment]
forget, my mistake, thanks man!!

**Comment by luisdalmolin** [comment]
@maiconmva Sem problemas! 😉
