### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by rickmacgillis** [kirschbaum-development/eloquent-power-joins#25]
I'm getting this error: `Fatal error: Uncaught BadMethodCallException: Call to undefined method Illuminate\Database\Eloquent\Builder::getSelect()`

The issue is that the `PowerJoins` trait tries to call `getSelect` in the `scopeJoinRelationship` method. The code giving me issues is using Laravel 6. Below is what I wrote when calling it.

`$recipients = UserData::joinRelationship('users')->where('resub_sent', false)->dd();`

Here's what `UserData` looks like.

```
use Illuminate\Database\Eloquent\Model;
use Kirschbaum\PowerJoins\PowerJoins;

class UserData extends Model
{
	use PowerJoins;
}
```
Full error:
```
Fatal error: Uncaught BadMethodCallException: Call to undefined method Illuminate\Database\Eloquent\Builder::getSelect() in [REDACTED]/vendor/illuminate/support/Traits/ForwardsCalls.php:50
Stack trace:
#0 [REDACTED]/vendor/illuminate/support/Traits/ForwardsCalls.php(36): Illuminate\Database\Eloquent\Builder::throwBadMethodCallException()
#1 [REDACTED]/vendor/illuminate/database/Eloquent/Builder.php(1377): Illuminate\Database\Eloquent\Builder->forwardCallTo()
#2 [REDACTED]/vendor/kirschbaum-development/eloquent-power-joins/src/PowerJoins.php(43): Illuminate\Database\Eloquent\Builder->__call()
#3 [REDACTED]/vendor/illuminate/database/Eloquent/Builder.php(986): [WordPressProj]\Models\UserData->scopeJoinRelationship()
#4 [REDACTED]/vendor/illuminate/database/Eloquent/Builder.php(1370): in [REDACTED]/vendor/illuminate/support/Traits/ForwardsCalls.php on line 50
```

Please note that this implementation is being used outside of a Laravel project, but it uses the following things inside composer.json.

```
"illuminate/database" : "^6.0",
"illuminate/filesystem" : "^6.0",
"illuminate/translation" : "^6.0",
"illuminate/validation" : "^6.0",
"illuminate/pagination" : "^6.0",
"kirschbaum-development/eloquent-power-joins" : "^2.1"
```
If I'm missing something that PowerJoins relies on, please let me know. It just seems strange that in the years I've been working with Laravel on this same project, that this would be the first time I'd have something missing that Eloquent ORM needs to function in a given way.

**Comment by luisdalmolin** [comment]
@rickmacgillis can you do a quick check and see if calling `::query()` first solves the issue?

```php
$recipients = UserData::query()->joinRelationship('users')->where('resub_sent', false)->dd();
```

I'll definitely take a look at this, but may take a few days.

**Comment by rickmacgillis** [comment]
Same issue, even using your code.

**Comment by luisdalmolin** [comment]
@rickmacgillis If this is being used outside a Laravel project, it's likely that the macros are not being registered correctly for some reason.

https://github.com/kirschbaum-development/eloquent-power-joins/blob/master/src/Mixins/QueryBuilderExtraMethods.php
https://github.com/kirschbaum-development/eloquent-power-joins/blob/master/src/EloquentJoins.php#L22

You may need to manually call the service provider or execute the `EloquentJoins` class manually? Not sure how this setup looks like.

**Comment by rickmacgillis** [comment]
@luisdalmolin You're probably right. I decided to just manually add the join code from stock Laravel, so in my case I'm not using PowerJoins right now or I'd try that suggestion. I greatly appreciate your responsiveness on this project, though.

**Comment by luisdalmolin** [comment]
No problem, I'm going to close this issue then. Feel free to re-open if you decide to try that approach and it fails.
