### ISSUE TITLE
issue with powerJoinHas

### ISSUE THREAD

**Issue by mcolominas** [kirschbaum-development/eloquent-power-joins#27]
When I try to use "powerJoinHas" I get the following error:

Country::powerJoinHas('translation')->get()

SQLSTATE[42000]: Syntax error or access violation: 1055 'countries.iso2' isn't in GROUP BY (SQL: select `countries`.*, count(country_translations.id) as country_translations_count from `countries` left join `country_translations` on `country_translations`.`country_id` = `countries`.`id` and `country_translations`.`locale` = en group by `countries`.`id` having country_translations_count >= 1 limit 1)

**Comment by luisdalmolin** [comment]
Hmm, you may need to set your MySQL strict configuration to `false` for this to work. This can be set on `config/database.php`. Can you test that and let me know?

**Comment by mcolominas** [comment]
Thank you, that was the problem.
