### ISSUE TITLE
Error when the relation has a function inside the where

### ISSUE THREAD

**Issue by mcolominas** [kirschbaum-development/eloquent-power-joins#29]
In my code, in the relation I have added a function inside the where, looking like this:

`return $this->hasOne($translateModel, $this->getForeignKey(), $this->getKeyName())->where(function ($q){
    ...
});`

And it gives me the following error:
Undefined index: column

I have looked a bit and the problem comes from the file "eloquent-power-joins/src/Mixins/RelationshipsExtraMethods.php" in the method "shouldNotApplyExtraCondition()",

Have a:
`return $condition['column'] === $key;`

But it has inside of "$condition":
`array:3 [▼
  "type" => "Nested"
  "query" => Illuminate\Database\Query\Builder {#1737 ▶}
  "boolean" => "and"
]`

**Comment by luisdalmolin** [comment]
@mcolominas Yeah, this seems a valid issue. I'll take a look when I can. If you have a solution already, feel free to send a PR.

**Comment by luisdalmolin** [comment]
@mcolominas This is now fixed in 2.2.1 - can you test?

**Comment by mcolominas** [comment]
@luisdalmolin No errors, thanks for correcting it so quickly, I hope I do not find more issues.
