### ISSUE TITLE
Nested where clauses in join clause cause Exception

### ISSUE THREAD

**Issue by timrosskamp** [kirschbaum-development/eloquent-power-joins#31]
Hey, I really like you extension! It helped me optimizing my queries a lot! But I came across an Exception when using nested where clauses inside a join clause:

```php
$query = Events::joinRelationship('dates', function ($join) use ($dateFrom, $dateTo) {
    $join->as('date')
        ->where(function ($query) use ($dateFrom) {
            $query->where("date.start", ">=", $dateFrom)
                ->orWhere("date.end", ">=", $dateFrom);
        })
        ->where("date.start", "<=", $dateTo);
});
```

The reason is that `PowerJoinClause::where` doesn't accept a Closure as it's first parameter. An Exception is thrown from the `Str::contains` function, because `$column` is not a string:

https://github.com/kirschbaum-development/eloquent-power-joins/blob/067f6db403f9ec613e2d02988e55f1b65b445734/src/PowerJoinClause.php#L116-L123

If you take a look at the method from the parent class `Illuminate\Database\Query\Builder::where`, you can see that the `$column` argument can be a Closure, which results in a nested where clause: https://github.com/laravel/framework/blob/2cd2877fb003d395b5b292a363b917e31cf60200/src/Illuminate/Database/Query/Builder.php#L695-L700

Do you think nested where clauses could be implemented?

If you don't have the time or my request would be too complicated, don't worry about it. I can find another way to build my query.

**Comment by luisdalmolin** [comment]
@timrosskamp This should be fixed in version 2.2.2, which was just published. I'm closing the issue, but feel free to reopen if you still have issues.
