### ISSUE TITLE
How to .

### ISSUE THREAD

**Issue by itsensepk** [kirschbaum-development/eloquent-power-joins#36]
Hello,

How would you return a result with powerjoins when you have an order table that belongs to customer can have employee and you also need to know the creator.

customer_id <-- references customers table to whom this order belongs to
employee_id <-- the order manager who is assigned to this order,
creator_id <-- user who created this order,
creator <-- user type customer/employee

currently i'm using raw query where i join both tables customers and employees for creator_id and then do if condition using value of creator column..

the scenerio is very specific but I was exploring your package so i thought you could help.

P.s I know I should move creator to different table.

Thanks in advance!

**Comment by luisdalmolin** [comment]
@itsensepk In this case, it seems that you could replace your raw joins by using the power joins, as long as your models have the relationships defined.

If you want to post your raw query, I can show you a quick example. I'm going to close this as this is a non-issue, but feel free to comment still.
