### ISSUE TITLE
nested powerJoinWhereHas failure 

### ISSUE THREAD

**Issue by itsensepk** [kirschbaum-development/eloquent-power-joins#38]
As powerJoinWhereHas expects instance of Illuminate\\Database\\Eloquent\\Builder, we are unable to use it in below query
```
return Category::with(['getBrands' => function ($brand) {
            $brand->distinct('brands.id')
            ->powerJoinWhereHas('products', function ($join) {
                return $join->where(['active' => true, 'website' => true])->powerJoinWhereHas('channel', function ($channel) {
                    return $channel->where(['active' => true, 'website' => true]);
                });
            })
            ->withCount('products');
        }])->withCount('products')->get();
```
this throws
`Argument 1 passed to App\\Models\\Product\\Product::scopePowerJoinWhereHas() must be an instance of Illuminate\\Database\\Eloquent\\Builder, instance of Kirschbaum\\PowerJoins\\PowerJoinClause given`

along with this issue, a not unique table/alias issue also occured when i tried again after removing nested powerJoinWherHas like :
```
return Category::with(['getBrands' => function ($brand) {
            $brand->distinct('brands.id')
            ->powerJoinWhereHas('products', function ($join) {
                return $join->where(['active' => true, 'website' => true]);
            })
            ->withCount('products');
        }])->withCount('products')->get();
```

both of the above queries works when used with default whereHas.

Thanks.

**Comment by luisdalmolin** [comment]
@itsensepk Thanks for reporting, I'll check this out over the weekend.

**Comment by luisdalmolin** [comment]
@itsensepk This is a complex issue that goes a bit on how Laravel works with joins under the hook. I'm afraid using the `powerJoinWhereHas` in nested queries like this will not be possible, at least not without a big re-thinking.

My suggestion for you is to use the regular `whereHas` in this case. I'm going to close this issue as there are no plans of supporting this for now.
