### ISSUE TITLE
PHP 8.0

### ISSUE THREAD

**Issue by asivaneswaran** [kirschbaum-development/eloquent-power-joins#42]
It seems that this package does not support PHP 8.0? Does it only support ^7.1 or ^8.1?

Any reason why 8.0 is skipped?

**Comment by luisdalmolin** [comment]
Ha, that was a mistake, I'll get it fixed.

**Comment by luisdalmolin** [comment]
@asivaneswaran This should be fixed on 2.3.1. Thanks for reporting.

**Comment by asivaneswaran** [comment]
Thanks!
