### ISSUE TITLE
Custom orderByPowerJoins

### ISSUE THREAD

**Issue by xicond** [kirschbaum-development/eloquent-power-joins#44]
How to orderByPowerJoins if the field is need like 
`DB::raw('concat(firstname, ' ', lastname)')`

**Comment by luisdalmolin** [comment]
@xicond The ability to do this was added in version 2.3.2. You can do like this:

```php
User::orderByPowerJoins(['profile', DB::raw('concat(city, ", ", state)']);
```

The first array item is the relationship, and the second your raw expression.
