### ISSUE TITLE
Call to undefined method Illuminate\Database\Eloquent\Builder::getSelect()

### ISSUE THREAD

**Issue by bianchi** [kirschbaum-development/eloquent-power-joins#46]
I'm getting this error:

`Call to undefined method Illuminate\Database\Eloquent\Builder::getSelect()`

My code call:
`EmpresaGrupo::joinRelationship('pessoa');`

I believe is the same as #43

I'm using Lumen 8

**Comment by luisdalmolin** [comment]
@bianchi Sorry the delay on getting back to you. Is your model using the `PowerJoins` trait? To be honest I didn't test this package with Lumen, but it should (in theory) work in the same way.

**Comment by bianchi** [comment]
@luisdalmolin thanks for answer. Yes, I'm using the trait

**Comment by bianchi** [comment]
Solved registering service provider. In my app.php:

`$app->register(Kirschbaum\PowerJoins\PowerJoinsServiceProvider::class);`
