### ISSUE TITLE
How to return/view joined relation?

### ISSUE THREAD

**Issue by notiv-nt** [kirschbaum-development/eloquent-power-joins#48]
I have a test project with user/post models

`User.php`
```
class User {
    use PowerJoins;

    public function posts() {
        return $this->hasMany(Post::class);
    }
}
```

`Post.php` is almost empty

Query
```
Route::get('/', function () {
    return User::joinRelationship('posts')->find(1);
});
```

And, i see

```
{
  "id": 1,
  "name": "Mrs. Elvera Considine MD",
  "email": "jerde.lowell@example.com",
  "email_verified_at": "2021-02-24T10:35:31.000000Z",
  "created_at": "2021-02-24T10:35:31.000000Z",
  "updated_at": "2021-02-24T10:35:31.000000Z"
}
```

How to return posts? `getPostsAttribute`? `$visible = []` ?

```
$user = User::joinRelationship('posts')->find(1);
return $user->posts;
```
Gives me a new db query `SELECT * FROM "posts" WHERE "posts"."user_id" = '1' and "posts"."user_id" IS not NULL`

How to use that ?

**Comment by luisdalmolin** [comment]
So, if you want to access the multiple posts your user can have, you won't really be able to use the joins here just by the nature of joins. You could use joins to select fields and/or filter results, but it seems like you aren't doing either. So, you should just stick with the default relationship.

If you want to return posts and this is an API endpoint, you should use eager loading:

```php
$user = User::with('posts')->find(1);
```
