### ISSUE TITLE
[2.3.3] call multi joinRelationship function query builder

### ISSUE THREAD

**Issue by phuongdm1987** [kirschbaum-development/eloquent-power-joins#51]
```$queryBuilder->joinRelationship('relationships', function ($query) use ($condition) {
            $query->where('status', 'ACTIVE');
        });

$queryBuilder->joinRelationship('relationships', function ($query) use ($condition) {
            $query->where('role', 'ADMIN');
        });```

The query just accept first condition, as I see in PowerJoins::scopeJoinRelationship, we check relationshipAlreadyJoined
So, this function will be return.
Please help to support multi where statement like above, I tried with order it work well.

**Comment by luisdalmolin** [comment]
I'm not sure I follow your issue. Can you be more specific on what is the error you are seeing, and also post the full code snippet?

**Comment by phuongdm1987** [comment]
```
$queryBuilder->joinRelationship('relationships', function ($query) use ($condition) {
          $query->where('user_relationships.host_id', 53');
      });

$queryBuilder->joinRelationship('relationships', function ($query) use ($condition) {
          $query->where('role', 'ADMIN');
      });
```

I've 2 classes to call `joinRelationship` twice with the same queryBuidler. But the query accepts only the first filter

select `users`.* from `users` inner join `user_relationships` on `user_relationships`.`client_id` = `users`.`id` and `user_relationships`.`host_id` = 53 order by `users`.`id` desc limit 20 offset 0

possible to join with multi conditions like above?

**Comment by Shadow505** [comment]
Hi,

I'm having a similar issue. Example:

```
		$purchase = Purchase::where('purchase_code', $purchaseCode)
		                    ->select(['products.product_name', 'serial_product.product_name as serial_product_name'])
		                    ->leftJoinRelationShip('product')
		                    ->leftJoinRelationShip('serial.product', [
			                    'product' => function ($join) use($productID) {
				                    $join->as('serial_product')->where('serial_product.id', $productID);
			                    }
		                    ])
		                    ->first();
```

Will fail with the error:

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'serial_product.product_name' in 'field list' (SQL: select `products`.`product_name`, `serial_product`.`product_name` as `serial_product_name` from `purchases` left join `products` on `purchases`.`product_id` = `products`.`id` left join `serials` on `serials`.`related_purchase_code` = `purchases`.`purchase_code` where `purchase_code` = test limit 1)`

That is because it ignores the second join statement.

**Comment by luisdalmolin** [comment]
@phuongdm1987 Got it. Yeah, in your case it would ignore the second condition indeed. You can, though, use a different approach, like:

```php
$queryBuilder->joinRelationship('relationships')
    ->where('user_relationships.host_id', 53');

$queryBuilder->joinRelationship('relationships')
    ->where('user_relationships.role', 'ADMIN');
```

You can use the condition outside the callback. This may be a feature we implement in the future, but I'd have to analyze as it may have unintended consequences.

**Comment by luisdalmolin** [comment]
@Shadow505 Your issue is different. `product_name` is not a column from the `serial_product` table, and because of that it's failing at the SQL level.

**Comment by Shadow505** [comment]
@luisdalmolin 

No, that's not the issue.

`product_name` is a column in the `products` table and has been aliased as `serial_product`. 

If I remove the first `leftJoinRelationShip` call, it does not produce the error (but then obviously misses the other data). The issue is definitely the caching feature.

**Comment by luisdalmolin** [comment]
@Shadow505 Yep that makes sense, I'll look into it.

**Comment by luisdalmolin** [comment]
@Shadow505 Your issue should be fixed in https://github.com/kirschbaum-development/eloquent-power-joins/releases/tag/2.4.0. Let me know if you still have the issue.

**Comment by phuongdm1987** [comment]
well, thanks all, 

> Hi,
> 
> I'm having a similar issue. Example:
> 
> ```
> 		$purchase = Purchase::where('purchase_code', $purchaseCode)
> 		                    ->select(['products.product_name', 'serial_product.product_name as serial_product_name'])
> 		                    ->leftJoinRelationShip('product')
> 		                    ->leftJoinRelationShip('serial.product', [
> 			                    'product' => function ($join) use($productID) {
> 				                    $join->as('serial_product')->where('serial_product.id', $productID);
> 			                    }
> 		                    ])
> 		                    ->first();
> ```
> 
> Will fail with the error:
> 
> ```
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'serial_product.product_name' in 'field list' (SQL: select `products`.`product_name`, `serial_product`.`product_name` as `serial_product_name` from `purchases` left join `products` on `purchases`.`product_id` = `products`.`id` left join `serials` on `serials`.`related_purchase_code` = `purchases`.`purchase_code` where `purchase_code` = test limit 1)
> ```
> 
> That is because it ignores the second join statement.

That is the point I want to show, thanks
If we call the same relationship join much time, the package only accepts the first one.

**Comment by Shadow505** [comment]
@luisdalmolin Thanks!

**Comment by Shadow505** [comment]
@luisdalmolin 

Hi, 

unfortunately I am having issues again with the caching feature. Take this example:

```
			->leftJoinRelationship('product', function($join) {
				$join->as('productPrevious')->where('productPrevious.product_version', '<', '1.0.0');
							})
			->leftJoinRelationship('product', function($join) {
				$join->as('productCurrent')->where('productCurrent.product_version', '=', '1.0.0');
			})
			->select(['productPrevious.product_version as productPreviousVersion', 'productCurrent.product_version as productCurrentVersion'])
```

I basically attempt to join the same table twice but with a different where() condition and then select the desired columns for both of them. Unfortunately, it will again ignore the second join, due to the caching feature.

Thanks for your help!
