### ISSUE TITLE
Issue with aliased joins

### ISSUE THREAD

**Issue by Shadow505** [kirschbaum-development/eloquent-power-joins#53]
Hey there,

I am having issues, using nested relationships that have been aliased. Take this example:

```
Purchase::where('purchases.id', 1)
			->leftJoinRelationShip('serial.product', [
				'serial' => function ($join) {
					$join->as('purchase_serial');
				},
				'product' => function ($join) {
					$join->as('purchase_product');
				},
			])
			->first();
```

This will produce the following error:

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'serials.product_id' in 'on clause' (SQL: select `purchases`.* from `purchases` left join `serials` as `purchase_serial` on `purchase_serial`.`code` = `purchases`.`purchase_code` left join `products` as `purchase_product` on `serials`.`product_id` = `purchase_product`.`id` where `purchases`.`id` = 1 limit 1)

That's because the `on` clause does not take the aliased table name into account.  So, insead of

```
on `serials`.`product_id` = `purchase_product`.`id`
```
it should actually be

```
on `purchase_serial`.`product_id` = `purchase_product`.`id`
```

I went ahead and tried to manually specify the `on` clause like this

```
Purchase::where('purchases.id', 1)
			->leftJoinRelationShip('serial.product', [
				'serial' => function ($join) {
					$join->as('purchase_serial');
				},
				'product' => function ($join) {
					$join->as('purchase_product')->on('purchase_serial.product_id', '=', 'purchase_product.id');
				},
			])
			->first();
```

Unfortunately this will append the on clause, instead of replacing it and will therefore result in this error:

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'serials.product_id' in 'on clause' (SQL: select `purchases`.* from `purchases` left join `serials` as `purchase_serial` on `purchase_serial`.`code` = `purchases`.`purchase_code` left join `products` as `purchase_product` on `serials`.`product_id` = `purchase_product`.`id` and `purchase_serial`.`product_id` = `purchase_product`.`id` where `purchases`.`id` = 1 limit 1)

Thanks for your time!

**Comment by jaulz** [comment]
Yep, same issue here 👎

**Comment by rubenlagatie** [comment]
Hi, I also bumped into this problem. I've quickly checked the code and I think an easy fix would be to add the alias to the aliasesCache on line 60 in PowerJoinClause.php:
`PowerJoins::$powerJoinAliasesCache[spl_object_id($this->model)] = $alias;`
There is already code that checks this cache when joining.
I've tested this and it seems to be working fine, even for nested aliases.

**Comment by luisdalmolin** [comment]
@rubenlagatie would you mind sending a PR with the fix?

**Comment by levi730** [comment]
@rubenlagatie Do you still have the fix for this issue?  Even if it's just some code snippets and not a real PR, I might be able to run with that.  I'm encountering the same problem, and it seems to be my only roadblock.  Thanks!

**Comment by rubenlagatie** [comment]
Sorry for the late reply, I am on holiday. The fix is as simple as I stated in my previous message, just add this line of code:
`PowerJoins::$powerJoinAliasesCache[spl_object_id($this->model)] = $alias;`
to PowerJoinClause.php on line 60.
By doing this, the alias is added to the aliasescache and will be used when the join statement is being created.
I can make a PR next week if you want.

**Comment by rubenlagatie** [comment]
Pull request created: https://github.com/kirschbaum-development/eloquent-power-joins/pull/63

**Comment by luisdalmolin** [comment]
This should be fixed on https://github.com/kirschbaum-development/eloquent-power-joins/releases/tag/2.4.1
