### ISSUE TITLE
Joining using Aliases

### ISSUE THREAD

**Issue by jreason** [kirschbaum-development/eloquent-power-joins#54]
I cannot get this to work at all.

my relationship is called salesExec.
`
public function salesExec()
    {
        return $this->hasOne(User::class, 'id', 'sales_exec_user_id');
    }
`

`$records = Order::leftJoinRelationship('salesExec')->select('users.first_name')->first();`
Works but no good when i need to join the users table again.

`$records = Order::leftJoinRelationshipUsingAlias('salesExec')->select('salesExec.first_name')->first();`
Does not work: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'salesExec.first_name'

`$records = Order::leftJoinRelationshipUsingAlias('salesExec')->select('sales_exec.first_name')->first();`
Does not work: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sales_exec.first_name'

`$records = Order::leftJoinRelationshipUsingAlias('salesExec')->select('users.first_name')->first();`
Does not work: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.first_name'

`$records = Order::leftJoinRelationshipUsingAlias('salesExec')->toSql();`

Seems to join as a random string, so have no way to select specifc columns
>select `orders`.* from `orders` left join `users` as `b69c457af5e262af3fe7823187d6beb7` on `b69c457af5e262af3fe7823187d6beb7`.`id` = `orders`.`sales_exec_user_id`

```
$records = Order::leftJoinRelationship('salesExec', [
            'salesExec' => function ($join) {
                $join->as('sales_exec');
            },
        ])->select('sales_exec.first_name')->first();
```
Does not work: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sales_exec.first_name'

```
$records = Order::leftJoinRelationship('salesExec', [
            'users' => function ($join) {
                $join->as('sales_exec');
            },
        ])->select('sales_exec.first_name')->first();
```
Does not work: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sales_exec.first_name'

Not quite sure what im doing wrong here?

On a separate note, it should be great to join using as alias like this:
```
$records = Order::leftJoinRelationshipUsingAlias('salesExec', 'sales_exec')
```
Instead of
```
$records = Order::leftJoinRelationship('salesExec', [
            'users' => function ($join) {
                $join->as('sales_exec');
            },
        ])->select('sales_exec.first_name')->first();
```

**Comment by luisdalmolin** [comment]
You are almost there - since you have only on relationship in your joinRelationship call (not nested), you don't need to pass an array as the second parameter and you can pass a closure directly:

```php
$records = Order::leftJoinRelationship('salesExec', function ($join) {
    $join->as('sales_exec');
})->select('sales_exec.first_name')->first();
```

Or, if you pass an array, you need to use as the array key, the relationship name:

```php
        $records = Order::leftJoinRelationship('salesExec', [
            'salesExec' => function ($join) {
                $join->as('sales_exec');
            },
        ])->select('sales_exec.first_name')->first();
```

**Comment by luisdalmolin** [comment]
If this doesn't work, let me know. The `$records = Order::leftJoinRelationshipUsingAlias('salesExec', 'sales_exec')` is a good idea, I may implement it.

**Comment by luisdalmolin** [comment]
This feature will be shipped in the next version which should go out today (hopefully).
