### ISSUE TITLE
powerJoinWhereHas doesn't call the callback function with hasOneThrough/hasManyThrough

### ISSUE THREAD

**Issue by mcolominas** [kirschbaum-development/eloquent-power-joins#55]
Hi, I am using 'powerJoinWhereHas' with a relation of 'hasOneThrough' or 'hasManyThrough', but it doesn't call the callback function, however, for example with a relation of 'hasMany', call the callback function.

**Comment by luisdalmolin** [comment]
@mcolominas Can you give me one example one how you are trying to pass the callback?

**Comment by luisdalmolin** [comment]
This was fixed on https://github.com/kirschbaum-development/eloquent-power-joins/releases/tag/2.5.2
