### ISSUE TITLE
Nested joins with different join type

### ISSUE THREAD

**Issue by heartbeatLV** [kirschbaum-development/eloquent-power-joins#58]
hi, thanks for your work

Is it possible to join nested relationships with different join types?

```php example
User::query()
    ->join('posts', 'posts.user_id', '=', 'users.id')
    ->leftJoin('comments', 'comments.post_id', '=', 'posts.id')
    ->toSql()
```

**Comment by luisdalmolin** [comment]
Currently, there's no way to explicitly do this, although it's probably a good feature to have. I believe you should be able to to something like this, though:

```php
User::query()
    ->joinRelationship('posts')
    ->leftJoinRelationship('posts.comments')
    ->toSql()
```

I'll put this in the roadmap of new features.

**Comment by heartbeatLV** [comment]
by doing so, the 'posts' relationship is joined twice

and in the reverse case it does not give the desired result:

``` php
User::query()
    ->leftJoin('posts', 'posts.user_id', '=', 'users.id')
    ->join('comments', 'comments.post_id', '=', 'posts.id')
    ->toSql()
```

**Comment by luisdalmolin** [comment]
So, the examples you are giving are not really using the package. This is something that will have to be added to the package eventually and won't be possible **with** the package until there.

**Comment by fabianogaldino** [comment]
A temporary solution would be to unset the extra join.

unset left join posts
```
foreach ($query->getQuery()->joins as $key => $join) {
    if ($join->table == Post::getModel()->getTable() && $join->type == 'left') {
        unset($query->getQuery()->joins[$key]);
    }
}
```

**Comment by luisdalmolin** [comment]
This solution should work just fine nowdays, so closing this issue:

```php
User::query()
    ->joinRelationship('posts')
    ->leftJoinRelationship('posts.comments')
    ->toSql()
```
