### ISSUE TITLE
Join disappears using withCount

### ISSUE THREAD

**Issue by azzumed** [kirschbaum-development/eloquent-power-joins#59]
Laravel dont merging joins, when using withCount method on relation.
I'm have hasMany relation, where i'm need joins, but i'm cant use it with withCount
Because this method, called from Builder::withCount->withAggregate
\Illuminate\Database\Eloquent\Concerns\QueriesRelationships::mergeConstraintsFrom

**Comment by luisdalmolin** [comment]
Can you post a code snippet so I can understand how you are calling the code? It's a bit hard to understand just from what you wrote

**Comment by luisdalmolin** [comment]
I'm closing this issue for now, feel free to reopen with an example.
