### ISSUE TITLE
compoships support

### ISSUE THREAD

**Issue by kevincobain2000** [kirschbaum-development/eloquent-power-joins#60]
Hi, do you have plans to support multiple keys for the packages such as https://github.com/topclaudy/compoships

**Comment by luisdalmolin** [comment]
There are no plans about it, but it's the first time I heard about this package. I'd have to look at their implementation, but my current thinking is that it would be too much work to make it work with 1 specific package. I'm closing the issue, but feel free to reopen if you think it should, and we are always open to PRs!

**Comment by kevincobain2000** [comment]
Thank you. 
You are open to PR that is nice. I will see what I can do.
