### ISSUE TITLE
Using this library with Capsule

### ISSUE THREAD

**Issue by Goddard** [kirschbaum-development/eloquent-power-joins#61]
Since Eloquent can be used as a stand alone ORM system how do you use this package when you aren't using Laravel?

**Comment by luisdalmolin** [comment]
In theory, the same way. This package has `illuminate/support` and `illuminate/database` as dependencies only. I never tried using even Eloquent outside of Laravel, so can't say this for sure. 

Did you try it and it didn't work? Any specific error message?

**Comment by Goddard** [comment]
Getting the same error as this issue.

https://github.com/kirschbaum-development/eloquent-power-joins/issues/46

**Comment by EgorGruzdev** [comment]
If you look at the source of the service provider for this package, it's enough to add a call to EloquentJoins::registerEloquentMacros() in addition to what is already described in illuminate/database;

**Comment by Goddard** [comment]
Alright sweet, was able to get it working by including that call in my base model.

**Comment by ccerrillo** [comment]
@luisdalmolin Maybe this can be in the usage instructions, i can confirm that this must be called if you are using illuminate/database  as standalone ORM
