### ISSUE TITLE
self relationship

### ISSUE THREAD

**Issue by mshamaseen** [kirschbaum-development/eloquent-power-joins#65]
I have `Admin` model with a relation called `inviter` which indicates the admin that invited this one to the system (self-relationship).

so the inviter relation is:

`function inviter()
    {
        return $this->belongsTo(self::class,'invited_by');
    }` 

calling : `joinRelationship('inviter')->find(1)` result on

```
Syntax error or access violation: 1066 Not unique table/alias: 'admins' (SQL: select `admins`.* from `admins` inner join `admins` on `admins`.`invited_by` = `admins`.`id` where `admins`.`id` = 1 limit 1)
```

**Comment by luisdalmolin** [comment]
@mshamaseen You will have to join this relationship using aliases:

```php
joinRelationshipUsingAlias('inviter')->find()
```

OR

```php
joinRelationship('inviter', fn ($join) => $join->as('admin_inviter'))->find()
```
