### ISSUE TITLE
Global scopes

### ISSUE THREAD

**Issue by thekonz** [kirschbaum-development/eloquent-power-joins#66]
I like this package, but global scopes are not applied to anything I join.

There is that hardcoded case of soft deletes, but no solution ready for other global scopes.

Is there a good way to add global scopes to a joined relation?

Example:
```php
class Bar extends Model {
    public function foos(): HasMany { }
}
class Foo extends Model {
    // hide all foo with hidden = 1
    use WithHiddenScope;
}

// all foo are considered, even the ones with hidden = 1
$bar = Bar::joinRelationship('foos');
```

**Comment by thekonz** [comment]
@luisdalmolin Did you have a look into this issue? Can you tell me if this will be solved by this package or not?
If not, I will try to work around this issue somehow.

**Comment by luisdalmolin** [comment]
@thekonz So, just to clarify, you are saying that the global scope from the joined model does not get applied in the join that was created by the package?

If that's the case, then it makes sense, I don't think the package is doing this, and it's definitely something we could implement. I may be able to look into it this weekend, but no promises. We are also open to PRs in case you are interested.

**Comment by thekonz** [comment]
I found a surprisingly easy way to implement it.

```php
// Taken from your readme:
User::joinRelationship('posts', function ($join) {
    $join->where('posts.approved', true);
})->toSql();

// Now we do the same, but apply all global scopes to the query
User::joinRelationship('posts', function ($join) {
    $join->where('posts.approved', true);
    
    $baseBuilder = $showsBuilder->getModel()->newQuery()->toBase();
    $join->mergeWheres($baseBuilder->wheres, $baseBuilder->bindings);
})->toSql();
```

So if the Post model contains an Active and a Published global scope, the resulting query would be:
```sql
select * from users
join posts on posts.user_id = users.id
and posts.active = 1
and posts.published = 1
group by users.id
```
Note that `posts.active` and `posts.published` will only have the table name, if you use `qualifyCol
umn` in the global scope or manually qualify it.

@luisdalmolin how would you want this to be implemented? Should joining eloquent relations contain global scopes by default or should that be configurable somehow?

**Comment by gisostallenberg** [comment]
If you'd just need to implement applying the global scopes of the relation, I took parts from @thekonz and created a class that can provide a closure.

```php
final class PowerJoinAddGlobalScope
{
    public function __invoke(FakeJoinCallback|PowerJoinClause|JoinClause $join): void
    {
        if (!$join instanceof PowerJoinClause) {
            return;
        }

        $query = $join->getModel()->newQuery()->toBase();
        $join
            ->mergeWheres($query->wheres, $query->bindings);
    }

    public static function create(
    ): \Closure {
        return (new static())(...);
    }
}
```

It can bu used as such:
```php
User::joinRelationship('posts', PowerJoinAddGlobalScope::create());
```

**Comment by gisostallenberg** [comment]
> Otherwise this would be a breaking change I don't want to deal with now

I think global scopes are meant to be applied in any case, unless disabled on purpose.
A path that does not introduce a breaking change would be to have a config option to enable this, which is set to `true` on install and kept on `false` on updates.
