### ISSUE TITLE
joinRelationshipCache breaks union query

### ISSUE THREAD

**Issue by thekonz** [kirschbaum-development/eloquent-power-joins#73]
I use an sql `union` statement to chain multiple queries together.
It all works great unless you join the same relation twice.

```php
$query1 = User::joinRelationship('posts');
$query2 = User::joinRelationship('posts.comments');
// errors: unknown column posts.id
$query1->union($query2)->get();
```

The resulting query is something like this:
```sql
select * from users
join posts on posts.user_id = user.id
union
select * from users
-- join on posts is missing here
join comments on comments.post_id = posts.id
```

I modified the method `\Kirschbaum\PowerJoins\PowerJoins::clearPowerJoinCaches` to also clear the `joinRelationshipCache` and it now works without an error.
```php
    public function clearPowerJoinCaches()
    {
        $this->joinRelationshipCache = []; // <- this is the new line
        PowerJoins::$powerJoinAliasesCache = [];

        return $this;
    }
```

**Comment by luisdalmolin** [comment]
Just tested and this works in the current version, so closing this issue.

**Comment by thekonz** [comment]
Alright thanks, I'll try it out next week and confirm that ;)
🚀
