### ISSUE TITLE
Join Using Alias

### ISSUE THREAD

**Issue by jreason** [kirschbaum-development/eloquent-power-joins#74]
Hi @luisdalmolin 

Just following up on #54 
I am still unable to get this to work correctly and im unsure where i am going wrong?

```
$records = Order::joinRelationshipUsingAlias('salesExec', 'salesExec')
            ->select([
                'orders.id',
                'orders.vehicle_reg',
                'orders.created_at',
                'salesExec.first_name'
            ])
            ->toSql();
```

Using ->get() i get the following error:

> Column not found: 1054 Unknown column 'salesExec.first_name' in 'field list'

When using ->toSql() i can see that its using a random string as the alias instead of salesExec?

> select `orders`.`id`, `orders`.`vehicle_reg`, `orders`.`created_at`, `salesExec`.`first_name` from `orders` inner join `users` as `be48e2c2f8d67d4ad035546f40ad055e` on `be48e2c2f8d67d4ad035546f40ad055e`.`id` = `orders`.`sales_exec_user_id`

I am using the latest version: 2.5.0

**Comment by jonneroelofs** [comment]
I have the same problem. Will create a PR to show a possible solution.
