### ISSUE TITLE
PHP 8.1 Support

### ISSUE THREAD

**Issue by ejunker** [kirschbaum-development/eloquent-power-joins#80]
I was testing my app with PHP 8.1 and got these deprecation notices.

`
Accessing static trait property Kirschbaum\PowerJoins\PowerJoins::$joinMethodsMap is deprecated, it should only be accessed on a class using the trait in /app/vendor/kirschbaum-development/eloquent-power-joins/src/PowerJoins.php on line 42
`

`
Accessing static trait property Kirschbaum\PowerJoins\PowerJoins::$powerJoinAliasesCache is deprecated, it should only be accessed on a class using the trait in /app/vendor/kirschbaum-development/eloquent-power-joins/src/PowerJoins.php on line 386
`

`
Accessing static trait property Kirschbaum\PowerJoins\PowerJoins::$powerJoinAliasesCache is deprecated, it should only be accessed on a class using the trait in /app/vendor/kirschbaum-development/eloquent-power-joins/src/Mixins/RelationshipsExtraMethods.php on line 305
`

**Comment by luisdalmolin** [comment]
Ok, seems like we need to do some work for this to work well with PHP 8. Not sure exactly when we'll get to this. If you are in a rush, we are open to PRs.

**Comment by luisdalmolin** [comment]
This should be working fine now in 2.6.3.
