### ISSUE TITLE
How i can get other users that have same interest of current user if empty then latest user

### ISSUE THREAD

**Issue by vipankumar87** [kirschbaum-development/eloquent-power-joins#81]
How i can get other users that have same interest of current user if empty then latest user

**Comment by luisdalmolin** [comment]
Sorry, I can't help you with the amount of informations you gave. If you need help, please describe your architecture with code examples.

**Comment by vipankumar87** [comment]
Interest Table
`
create table interests
(
    id         bigserial
        primary key,
    name       varchar(255) default ''::character varying not null,
    post_count bigint       default '0'::bigint,
    created_at timestamp(0),
    updated_at timestamp(0),
    deleted_at timestamp(0)
);
`

User_interest Pivot Table


`create table user_interest
(
    user_id     bigint not null
        constraint user_interest_user_id_foreign
            references users
            on delete cascade,
    interest_id bigint not null
        constraint user_interest_interest_id_foreign
            references interests
            on delete cascade
);`


User Table 


`create table users
(
    id                bigserial
        primary key,
    name              varchar(255) not null,
    email             varchar(255) not null
        constraint users_email_unique
            unique,
    email_verified_at timestamp(0),
    password          varchar(255) not null,
    remember_token    varchar(100),
    created_at        timestamp(0),
    updated_at        timestamp(0),
    username          varchar(255) not null
        constraint users_username_unique
            unique,
    profile_status    varchar(255) default '0'::character varying
);`

**Comment by vipankumar87** [comment]
I am login with ABC having interest in sport

now want to show user that have interest in sport
