### ISSUE TITLE
Laravel 9 and PHP 8.1

### ISSUE THREAD

**Issue by gianmarx** [kirschbaum-development/eloquent-power-joins#91]
Is Release 2.6.1 compatible with Laravel 9.0 and PHP 8.1?

**Comment by luisdalmolin** [comment]
Version [2.6.0](https://github.com/kirschbaum-development/eloquent-power-joins/releases/tag/2.6.0) should be, but it wasn't tested a lot since we didn't upgrade our internal projects using it yet. If you have any issues let me know.

**Comment by luisdalmolin** [comment]
This should be working fine now in 2.6.3.
