### ISSUE TITLE
Nested joins with belongs to many relations

### ISSUE THREAD

**Issue by wangarrius** [kirschbaum-development/eloquent-power-joins#98]
Hi,

I use 
```php  
->JoinRelationship('groups.roles.permissions.module', $powerJoinClause);
```
with 

```php  
        $powerJoinClause = [
            'permissions' => [
                'permissions' => function ($join) use ($permissionName) {
                    $join->name($permissionName);
                },
            ],
            'module' => function ($join) use ($moduleName) {
                $join->name($moduleName);
            }
        ];
```
in my code. 'permission' is a belongs to many relation. This already worked. But with the newest version of eloquent-power-joins i get the error 'Array callback must have exactly two elements'. The error seems to occur in line 437 in the PowerJoins.php
```php  
            if (is_array($callback) && isset($callback[$tableName])) {
                $fakeJoinCallback = new FakeJoinCallback();
                $callback[$tableName]($fakeJoinCallback);

                if ($fakeJoinCallback->getAlias()) {
                    return $fakeJoinCallback->getAlias();
                }
            }
```
because $callback[$tableName] is an array in this case.

But if I change the line 138 in the PowerJoins.php file from
```php  
 $alias = $this->getAliasName($useAlias, $relation, $relationName, $relation->getQuery()->getModel()->getTable(), $callback);
```
to
```php  
 $alias = $this->getAliasName($useAlias, $relation, $relationName, $relation->getQuery()->getModel()->getTable(), $relationCallback);
```
(change $callback to $relationCallback) everything works as expected.

**Comment by luisdalmolin** [comment]
@wangarrius are you using the latest version? Just to make sure. I'm going to take a look at this if so

**Comment by wangarrius** [comment]
@luisdalmolin I am using version 2.6.4.

**Comment by beshoo** [comment]
@luisdalmolin  any update on this? can we consider it a bug?

**Comment by luisdalmolin** [comment]
Can you verify if this is still an issue with 3.0.0? Feel free to reopen if so
